# https://docs.github.com/en/actions/learn-github-actions/contexts
name: Contexts
on: workflow_dispatch
jobs:
  view:
    runs-on: ubuntu-latest
    steps: 
    - name: view github Context
      run: echo "${{ toJSON(github) }}"
    - name: view job Context
      run: echo "${{ toJSON(job) }}"
    - name: view secrets Context
      run: echo "${{ toJSON(secrets) }}"
    - name: view needs Context
      run: echo "${{ toJSON(needs) }}"

