name: Continue on error

on:
  workflow_dispatch:

jobs:
    create_file:
        runs-on: ubuntu-latest
        steps:
        - name: Create File
          run: |
           touch test.txt
           echo "Hello, world" >> test.txt
        - name: Read File Contents
          id: file-read
          continue-on-error: true
          # test.sh file not exists. Without `continue-on-error: true` the whole job will fail.
          run: |
            cat test.sh       
        - name: Remove file
          run: |
            rm -rf text.txt
        - name: List file 
          run: | 
            ls -la 

               
        