# https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
name: Outputs
on: workflow_dispatch
jobs:
  task-1:
    runs-on: ubuntu-latest
    outputs: 
        output1: ${{steps.step1.outputs.greeting}}   # steps.<step-id>.outputs.<output-key>
        ending_greet: ${{steps.ending_step.outputs.ending_msg}}   # steps.<step-id>.outputs.<output-key>
    steps: 
    - name: greeting
      id: step1
      run : |
        echo "greeting=Hello World" >> "$GITHUB_OUTPUT"
    - name: ending
      id: ending_step
      run : echo "ending_msg=Take Care" >> "$GITHUB_OUTPUT"

  task-2:
    runs-on: ubuntu-latest
    needs: task-1
    steps:
    - name: get greeting from task-1
      env: 
        GREETING: ${{ needs.task-1.outputs.output1 }}
      run: echo "$GREETING"
    - name: get ending msg from task-1
      run: echo ${{ needs.task-1.outputs.ending_greet}}