name: matrix with include and exclude
on:
    #push:
    workflow_dispatch:

jobs:
  
  build:
    continue-on-error: true # continue running the build process even if any of the version failed
    strategy:
        max-parallel: 2   # To set the maximum number of jobs that can run simultaneously when using a matrix job strategy,
        matrix:
            go-version: ["1.20", "1.21"]
            os: ["ubuntu-latest","windows-latest"]
            include:
              - go-version: "1.19"
                os: ["ubuntu-latest"]
                # key: value <---- other new key can be added" 
            exclude:
               - go-version: "1.21"
                 os: "windows-latest"
                 
    runs-on: ${{ matrix.os }} # <-----------------------------
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}        # <-----------------
          cache-dependency-path: simple-task/go.sum

      - name: Build
        working-directory: ./simple-task
        run: |
         go build -v .
