name: Reusable
on:
  workflow_call:

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: |
          touch test.txt
          echo "Hello, World" > test.txt
          cat test.txt