name: Reusable
on:
  workflow_call:
    inputs:
      file_name:
        required: true
        type: string
    secrets:
        token:
          required: true

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: |
          touch ${{ inputs.file_name }}
          echo "Hello, World" > ${{ inputs.file_name }}
          cat ${{ inputs.file_name }}

      - name: secret used
        run: |
         cat ${{ secrets.token }}