name: reusable_02_deploy_to_s3
on: 
    workflow_call:
      inputs:
        artifact-name:
            description: The name of the artifact
            required: true
            default: artifact
            type: string

jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Get artifacts
          uses: actions/download-artifact@v3
          with:
            name: ${{ inputs.artifact-name }}
        - name:
          run: |
            ls -la
        - name: Configure AWS credentials 
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            aws-region: ${{ secrets.AWS_REGION }}
        - name: Copy files to the test website with the AWS CLI
          run: |
            aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }}
        