name: reusable_02
on: 
    workflow_call:
jobs:    
  deploy:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    # permissions:
    #     id-token: write
    #     contents: read
    steps:
        - name: Get artifacts
          uses: actions/download-artifact@v3
          with:
            name: webapp-artifact
        - name:
          run: |
            ls -la
        # - name: Configure AWS credentials 
        #   uses: aws-actions/configure-aws-credentials@v2
        #   with:
        #     role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        #     aws-region: ${{ secrets.AWS_REGION }}
        # - name: Copy files to the test website with the AWS CLI
        #   run: |
        #     aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }}
        