name: checkout test

on:
    push: 
        branches:
           - main
           - dev
    workflow_dispatch:
jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code        # branch name
        uses: actions/checkout@v3  # echo ${GITHUB_REF} refs/heads/main
      - name: view                 # echo ${GITHUB_REF##*/}  main
        run: |
         echo ${GITHUB_REF} 
         echo ${GITHUB_REF##*/}

  different_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Download Code
      uses: actions/checkout@v3
      with:
        ref: $GITHUB_REF##*/
        
