name: checkout test

on:
    push: 
        branches:
           - main
           - dev
    workflow_dispatch:
jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code        # branch name
        uses: actions/checkout@v3  # echo ${GITHUB_REF} refs/heads/main
      - name: view                 # echo ${GITHUB_REF##*/}  main
        run: |
         echo ${GITHUB_REF} 
         echo ${GITHUB_REF##*/}

  different_branch:
    name:  branch ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
    - name: Download Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

  another_branch:
   name: branch ${{ github.head_ref }}
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}