name: checkout test

on:
    push: 
        branches:
           - main
           - dev

    pull_request_target:
        branches:
          - main
          - dev
        types:
          ["closed"]

    workflow_dispatch:

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code        # branch name
        uses: actions/checkout@v3  # echo ${GITHUB_REF} refs/heads/main
      - name: view                 # echo ${GITHUB_REF##*/}  main 
        run: |
         echo ${GITHUB_REF} 
         echo ${GITHUB_REF##*/}

  on_push:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    name:  branch ${{ github.ref }} # refs/heads/main or refs/heads/dev
    runs-on: ubuntu-latest
    steps:
    - name: Download Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - run: |
       ls -la

  yet_another:
   if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
   name: branch ${{ github.ref_name }} # main or dev
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
    - run: |
        ls -la

  and_another:
   if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
   name: ${{ github.event.pull_request.head.ref }} - PR repo and branch 
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}  # PR - branch
        repository: ${{ github.event.pull_request.head.repo.full_name }} # PR - repo
    - run: |
        ls -la
        echo ${{ github.event.pull_request.head.ref }}

  once_more:
   if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
   name: branch ${{ github.base_ref}}
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.base_ref }}  
    - run: |
        ls -la
        echo ${{ github.base_ref}}