name: checkout test

on:
    push: 
        branches:
           - main
           - dev
    workflow_dispatch:
jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/checkout@v3
      - name: view
        run: |
          echo ${GITHUB_REF}

  different_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Download Code
      uses: actions/checkout@v3
      with: 
        path: dev
    
        
        
