name: generate-artifact-s3-upload

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/checkout@v3
      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: simple-task/go.sum
      - name: Execute test
        working-directory: ./simple-task
        run: go test -v .
   
  build:
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - name: Download Code
        uses: actions/checkout@v3
      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: simple-task/go.sum
      - name: Build
        working-directory: ./simple-task
        run: go build -v webapp
      - name: view files
        run: |
         ls -la
         cd simple-task
         ls -la
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with: 
            name: webapp-artifact
            path: ./simple-task/webapp

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
        id-token: write
        contents: read
    steps:
        - name: Get artifacts
          uses: actions/download-artifact@v3
          with:
            name: webapp-artifact
        - name: Configure AWS credentials 
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            aws-region: ${{ secrets.AWS_REGION }}
        - name: Copy files to the test website with the AWS CLI
          run: |
            aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }}
        
