# https://github.com/actions/cache
# Examples by language: https://github.com/actions/cache#implementation-examples
name: Caching - Golang
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/checkout@v3
      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
            go-version-file: simple-task/go.mod
            cache-dependency-path: simple-task/go.sum
      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
                ~/.cache/go-build
                ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
      - name: Test
        working-directory: ./simple-task
        run: go test -v .
   
  build:
    # This job depends on the successful completion of the 'test' job.
    # It will run only if the 'test' job finishes successfully.
    needs: test
    runs-on: ubuntu-latest
    steps: 
      # Step 1: Download the code from the repository.
      - name: Download Code
        uses: actions/checkout@v3
      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
            path: |
              ~/.cache/go-build
              ~/go/pkg/mod
            key: ${{ runner.os }}-golang-${{ hashFiles('./simple-task/go.sum') }}
      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version-file: simple-task/go.mod
          cache-dependency-path: simple-task/go.sum
      
      # Step 3: Build the project using 'go build' command.
      - name: Build
        working-directory: ./simple-task
        run: go build -v .
