name: Conditional Basic Job

on:
  workflow_dispatch

jobs:
    create_file:
        runs-on: ubuntu-latest
        steps:
        - name: Create File
          run: |
           touch test.txt
           echo "Hello, world" >> test.txt
        - name: Read File Contents
          id: file-read
          run: |
            cat test.txt
        - name: Remove file
          if: steps.file-read.outcome == 'success'
          run: |
            rm -rf text.txt
        - name: List file 
          if: steps.file-read.outcome == 'failure'
          run: | 
            ls -la 

               
               