name: ci

on:
 workflow_dispatch:
 #push:

jobs:
    test: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: '14.x'
            - name: Install dependencies
              run: npm ci
            - name: Run test
              run: npm test
    build:
        needs: test
        runs-on: ubuntu-latest
        env:
          IMAGE_TAG: ${{ github.sha }}
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build and push
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: |
                ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.API_IMAGE }}:${{ env.IMAGE_TAG }}
                ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.API_IMAGE }}:latest
                ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.TASK_IMAGE }}:${{ env.IMAGE_TAG }}
                ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.TASK_IMAGE }}:latest

 
