name: Go

on:
  push:
    paths:
      - simple-task/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: change directory
      run: cd simple-task

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./simple-task/...

    - name: Test
      run: go test -v ./simple-task/...
