name: Go

on:
  push:
    paths:
      - simple-task/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        cd simple-task
        ls -la
        go build -v ./..

    - name: Test
      run: |
        cd simple-task
        ls -la
        go test -v ./..
        
