name: matrix test
on:
    push:
    workflow_dispatch:


jobs:
  build:
    strategy:
        matrix:
            go-version: ["1.20", "1.21"]
            os: ["ubuntu-latest","windows-latest"]
    runs-on: ${{ matrix.os }} # <-----------------------------
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}        # <-----------------
          cache-dependency-path: simple-task/go.sum

      - name: Build
        working-directory: ./simple-task
        run: |
          go build -t .
