name: Reusable
on:
    push:
    workflow_dispatch:

jobs:
    script:
        runs-on: ubuntu-latest
        steps:
            - name: List files
              run: |
               ls -la
            - name: call reusable workflow
              uses: shamimice03/github-actions-lab/.github/workflows/reusable.yaml
